# Generated by Django 4.2.1 on 2023-05-18 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
