# Generated by Django 4.2.1 on 2023-05-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromMail', models.EmailField(max_length=100)),
                ('sendto', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(default='Sent', max_length=100)),
            ],
        ),
    ]
