# Generated by Django 4.2.1 on 2023-05-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0004_alter_message_frommail'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default='06:21', null=True),
        ),
    ]
