# Generated by Django 4.2.1 on 2023-05-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0008_alter_message_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendto', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(default='Draft', max_length=100)),
                ('fromMail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailapp.userregistration')),
            ],
        ),
    ]
