# Generated by Django 4.2.1 on 2023-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocking_user_id', models.CharField(max_length=100)),
                ('blocked_user_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Blocked', max_length=100)),
            ],
        ),
    ]
